main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.welcome_view, name='welcome'),
    path('mamuriyat', views.mamuryat, name='mamuriyat'),
    path('news', views.news_view, name="news"),
    path('new/<int:pk>/', views.new, name='new'),
    path('xodim', views.xodim, name='xodim'),
    path('oquv_reja', views.oquv_reja_view, name="oquv_reja"),
    path('tavsifnoma', views.tavsfinoma_view, name="tavsifnoma"),
    path('talab', views.talablar_view, name="talablar"),
    path('jadval', views.dars_jadval_view, name='jadval'),

]

oquv_tsdi_uz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from main.views import none_page

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('<str:name>/', none_page),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField


class New(models.Model):
    title = models.CharField(max_length=255, verbose_name="Title")  # Translation
    content = models.TextField(verbose_name="Content")  # Translation
    image = models.ImageField(upload_to="./news/", default="./news/news.png")

    create_at = models.DateTimeField(auto_now_add=True)
    upload_at = models.DateTimeField(auto_now=True)

    sees = models.IntegerField(default=65)

    def __str__(self):
        return self.title


class Course(models.Model):
    name = models.CharField(max_length=50, verbose_name="Kurs")  # Translation

    def __str__(self):
        return self.name


class Faculty(models.Model):
    name = models.CharField(max_length=50, verbose_name="Nomi")  # Translation
    sub_name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Curriculum(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    course = models.ManyToManyField(Course)
    file = models.FileField(upload_to="./oquv/")

    def __str__(self):
        return self.file.name


class CourseShip(models.Model):
    curriculum = models.ForeignKey(Curriculum, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)


class Description(models.Model):
    """Malaka tavsifnomasi"""
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    file = models.FileField(upload_to="./description/")

    def __str__(self):
        return self.file.name


class Requirement(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    file = models.FileField(upload_to="./requirements/")

    def __str__(self):
        return self.file.name


class StudentTable(models.Model):  #Dars jadvali
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    file = models.FileField(upload_to='./jadval/')

    def __str__(self):
        return self.file.name

main/views.py
from django.shortcuts import render
from .models import Faculty, Course, Curriculum, New, Description, Requirement, StudentTable


def welcome_view(request):
    news = New.objects.all()
    content = {
        'news': news
    }
    return render(request, 'main/welcome.html', content)


def mamuryat(request):
    return render(request, 'main/mamuryat.html')


def xodim(request):
    return render(request, 'main/xodim.html')


def oquv_reja_view(request):
    faculties = Faculty.objects.all()
    course = Course.objects.all()
    curriculums = Curriculum.objects.all()
    content = {
        'faculties': faculties,
        'courses': course,
        'curriculums': curriculums,
    }
    return render(request, 'main/oquv_reja.html', content)


def news_view(request):
    news = New.objects.all()
    return render(request, 'main/news.html', {'news': news})


def new(request, pk):
    new = New.objects.get(pk=pk)
    return render(request, 'main/new.html', {'new': new})


def tavsfinoma_view(request):
    descriptions = Description.objects.all()
    return render(request, 'main/tavsifnoma.html', {'descriptions': descriptions})


def talablar_view(request):
    requirements = Requirement.objects.all()
    return render(request, 'main/talablar.html', {'requirements': requirements})


def dars_jadval_view(request):
    faculties = Faculty.objects.all()
    courses = Course.objects.all()
    student_tables = StudentTable.objects.all()
    content = {
        'faculties': faculties,
        'courses': courses,
        'student_tables': student_tables
    }
    return render(request, 'main/jadval.html', content)


def none_page(request, name):
    return render(request, 'main/none_page.html', {'name': name})

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'image/logotip.ico' %}">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="theme-color" content="#000000">
    <meta name="description" content="Toshkent Davlat Stomatologiya Instituti">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="/static/css/style.css" rel="stylesheet">
    <title>O'quv Uslubiy </title>
</head>
<body>
<div id="root">
    <div class="App">
        <div class="top-head">
            <div class="content">
                <nav><p><i class="fa fa-fax"></i> +998(91) 123-45-67</p>
                    <p><i class="fa fa-envelope"></i> info@tsdi.uz</p></nav>
                <nav>
                    <ul class="messenger-lists">
                        <li><a href="https://t.me/tsdi_official"><i class="fa fa-paper-plane cltg"></i></a></li>
                        <li><a href="/"><i class="fa fa-twitter cltwitter"></i></a></li>
                        <li><a href="/"><i class="fa fa-facebook clfacebook"></i></a></li>
                        <li><a href="/"><i class="fa fa-instagram clinsta"></i></a></li>
                        <li><a href="/"><i class="fa fa-youtube clyoutube"></i></a></li>
                    </ul>
                    <p>
                        <i class="fa fa-fork"></i>
                        Uzbek
                    </p>
                    <p><a href="/admin">
                        Tizimga kirish
                        <i class="fa fa-sign-out"></i>
                    </a>

                    </p>
                </nav>
            </div>
        </div>
        <div class="list-head">
            <div class="content">
                <ul class="lists">
                    <li class="list"><a href="{% url 'main:welcome' %}"><p>Bosh sahifa</p></a></li>
                    <li class="list"><a href="{% url 'main:mamuriyat' %}"><p>Ma'muriyat</p></a></li>
                    <li class="list"><a href="{% url 'main:xodim' %}"><p>Xodimlar</p></a></li>
                    <li class="list"><a href="{% url 'main:oquv_reja' %}">O'quv rejalar</a></li>
                    <li class="list"><a href="{% url 'main:tavsifnoma' %}"><p>Malaka tavsifnomasi</p></a></li>
                    <li class="list"><a href="{% url 'main:talablar' %}"><p>Malaka talablar</p></a></li>
                    <li class="list"><a href="{% url 'main:jadval' %}"><p>Dars jadvali</p></a></li>
                    <li class="list"><a href="{% url 'main:news' %}"><p>Yangiliklar</p></a></li>
                </ul>
            </div>
        </div>

        {% block content %}

        {% endblock %}

        <!-- Start Footer -->
        <div class="footer">
            <div class="content">
                <div class="foot">
                    <h3>Ijtimoiy tarmoqlar</h3>
                    <nav class="effect"></nav>
                    <ul class="messenger-list">
                        <li><a href="https://t.me/tsdi_official"><i class="fa fa-paper-plane cltg"></i>Telegram</a></li>
                        <li><a href="/"><i class="fa fa-twitter cltwitter"></i>Twitter</a></li>
                        <li><a href="/"><i class="fa fa-facebook clfacebook"></i>Facebook</a></li>
                        <li><a href="/"><i class="fa fa-instagram clinsta"></i>Instagram</a></li>
                        <li><a href="/"><i class="fa fa-youtube clyoutube"></i>Youtube</a></li>
                    </ul>
                </div>
                <div class="foot"><h3>Bizning manzil</h3>
                    <nav class="effect"></nav>
                    <ul class="messenger-list">
                        <li><a><i class="fa fa-map-marker cltg"></i>103, Taraqqiyot ko'chasi, Toshkent .sh</a></li>
                        <li><a><i class="fa fa-phone clfacebook"></i>+998(91 151-31-17)</a></li>
                        <li><a><i class="fa fa-fax cltwitter"></i>+998(91 151-31-17)</a></li>
                        <li><a><i class="fa fa-envelope clfax"></i>info@tsdi.uz</a></li>
                        <li><a><i class="fa fa-globe cltg"></i>www.tsdi.uz</a></li>
                    </ul>
                </div>
                <div class="foot">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d20120.112689896025!2d69.296945!3d41.310068!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x41490626bc752d26!2sToshkent%20davlat%20stomatologiya%20instituti%20eski!5e1!3m2!1sen!2sus!4v1671468313818!5m2!1sen!2sus"
                            width="100%" height="250" frameborder="0" allowfullscreen="" aria-hidden="false"
                            tabindex="0" style="border: 1px;"></iframe>
                </div>
            </div>
            <div class="content"><p class="alert">Barcha huquqlar himoyalangan. Saytdagi barcha huquqlar O'zbekiston
                Respublikasi qonunlariga, shu jumladan mualliflik huquqi va turdosh huquqlarga muvofiq himoya qilinadi.
                Sayt materiallaridan foydalanganda, Toshkent davlat stomatologiya instituti saytiga havola ko'rsatilishi
                shart. Diqqat! Agar siz matnda xatoliklarni aniqlasangiz, ularni belgilab, web sayt ma'murini xabardor
                qilish uchun biz bilan bog'lanishingizni so'raymiz</p></div>
        </div>
    </div>
</div>
{#<script defer="defer" src="/static/js/script.js"></script>#}

</body>
</html>

templates/main/jadval.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="oquv_reja">
        <div class="top-content">
            <div class="content">
                <nav class="top-bar">
                    <h3>
                        <i class="fa fa-users"></i>
                        Dars javdal
                    </h3>
                    <nav>
                        <a href="{% url 'main:welcome' %}">
                            <i class="fa fa-home clfacebook"></i>
                        </a>/
                        <i><a class="clfacebook" href="{% url 'main:jadval' %}">
                            dars jadval
                        </a></i>
                    </nav>
                </nav>
            </div>
        </div>
        <div class="content"><br><br>
            <!-- Fakultetlar bo'yicha boshlandi -->
            {% for faculty in faculties %}
                <p class="div-fakultet">{{ faculty.name }}</p>
                {% for student_table in student_tables %}
                    {% if student_table.faculty == faculty %}
                        <div class="fakulty-box">
                            <!-- Kurslar bo'yicha boshlandi -->
                            {% for course in courses %}
                                {% if course == student_table.course %}
                                    <a href="{{ curriculum.file.url }}">
                                        <nav class="file-box">
                                            <img class="file-img" src="{% static 'image/book.png' %}" alt="file.png">
                                            <p class="file-text">
                                                <br> {{ faculty.name_uz }} {{ course.name_uz }} dars jadval</p>
                                        </nav>
                                    </a>
                                {% endif %}
                            {% empty %}
                                <a href="#">
                                    <nav class="file-box">
                                        <img class="file-img" src="{% static 'image/book.png' %}" alt="file.png">
                                        <p class="file-text">
                                            <br> {{ faculty.name_uz }} {{ course.name_uz }} dars jadval
                                        </p>
                                    </nav>
                                </a>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% empty %}
                    <p class="file-text">
                        {{ faculty.name_uz }} dars jadval kiritilmagan :)
                    </p>
                {% endfor %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="yangiliklar">
        <div class="top-content">
            <div class="content">
                <nav class="top-bar">
                    <h3>
                        <i class="fa fa-users"></i>
                        Bo`lim yangilik va e`lonlari
                    </h3>
                    <nav>
                        <a href="{% url 'main:welcome' %}">
                            <i class="fa fa-home clfacebook"></i>
                        </a>
                        /
                        <i>
                            <a class="clfacebook" href="{% url 'main:news' %}">
                                yangiliklar
                            </a>
                        </i>
                        /
                        <i>
                            <a class="clfacebook" href="{% url 'main:news' %}">
                                yangilik
                            </a>
                        </i>
                    </nav>
                </nav>
            </div>
        </div>
        <!-- yangilik start -->
        <div class="content news-content">
            <img src="{{ new.image.url }}" alt="rasm" style="width: 100%">
            <br><br>
            <hr>
            <h2>
                {{ new.title }}
            </h2>
            <hr>
            <p style="padding-bottom: 10px;">
                {{ new.content }}
            </p>
            <hr>
            <nav class="new-time">
                <em>
                    Yangilik |
                </em>
                {{ new.create_at | date:"d:m:Y" }}
                <i class="fa fa-eye">
                    {{ new.sees }}
                </i>
            </nav>
        </div>
    <!-- Yangilik tugadi -->
    </div>
{% endblock %}

templates/main/news.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="yangiliklar">
        <div class="top-content">
            <div class="content">
                <nav class="top-bar">
                    <h3>
                        <i class="fa fa-users"></i>
                        Bo`lim yangilik va e`lonlari
                    </h3>
                    <nav>
                        <a href="{% url 'main:welcome' %}">
                            <i class="fa fa-home clfacebook"></i>
                        </a>
                        /
                        <i>
                            <a class="clfacebook" href="{% url 'main:welcome' %}">
                                xodim
                            </a>
                        </i>
                    </nav>
                </nav>
            </div>
        </div>

        <div class="content news-content">
            {% for new in news %}
                <!-- Yangiliklar boshlandi -->
                <nav class="new-body">
                    <nav class="new-time"><em>Yangilik |</em> {{ new.create_at | date:"d:m:Y" }} <i class="fa fa-eye">
                        {{ new.sees }}</i></nav>
                    <nav class="news-img"><img src="{{ new.image.url }}" alt="rasm"></nav>
                    <p class="new-text">
                        <a href="{% url 'main:new' new.pk %}">
                            {{ new.title|slice:160 }}
                        </a>
                    </p>
                </nav>
            {% empty %}
                <h2 style="text-align: center; justify-content: center;">Yangiliklar yo'q</h2>
            {% endfor %}
        <!-- Yangiliklar tugadi -->
        </div>
    </div>
{% endblock %}

templates/main/none_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="malaka">
        <div class="top-content">
            <div class="content">
                <nav class="top-bar">
                    <h3>
                        <i class="fa fa-users"></i>
                        {{ name }}
                    </h3>
                    <nav>
                        <a href="{% url 'main:welcome' %}">
                            <i class="fa fa-home clfacebook"></i>
                        </a>/
                        <i>
                            <a class="clfacebook" href="{% url 'main:welcome' %}">
                                {{ name }}
                            </a>
                        </i>
                    </nav>
                </nav>
            </div>
        </div>
        <!-- Malaka tavsifnoma -->
        <div class="content">
            <h2 style="height: 200px; text-align: center; justify-items: center;">
                {{ name }}: not found...
            </h2>

        </div>
    </div>
{% endblock %}

templates/main/oquv_reja.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="oquv_reja">
        <div class="top-content">
            <div class="content">
                <nav class="top-bar">
                    <h3>
                        <i class="fa fa-users"></i>
                        O`quv rejalar
                    </h3>
                    <nav>
                        <a href="{% url 'main:welcome' %}">
                            <i class="fa fa-home clfacebook"></i>
                        </a>
                        /
                        <i>
                            <a class="clfacebook" href="{% url 'main:welcome' %}">
                                o`quv rejalar
                            </a>
                        </i>
                    </nav>
                </nav>
            </div>
        </div>
        <div class="content">
            <br><br>
            <!-- O'quv rejalar boshlandi -->
            {% for faculty in faculties %}
                <p class="div-fakultet">{{ faculty.name }}</p>
                {% for curriculum in curriculums %}
                    {% if curriculum.faculty == faculty %}
                        <div class="fakulty-box">
                            {% for course in curriculum.course.all %}
                                <a href="{{ curriculum.file.url }}">
                                    <nav class="file-box">
                                        <img class="file-img" src="{% static 'image/book.png' %}" alt="file.png">
                                        <p class="file-text">2022-2023 <br> {{ faculty.name_uz }} {{ course.name_uz }}
                                        </p>
                                    </nav>
                                </a>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endfor %}
            {% empty %}
                <h2 style="height: 200px; text-align: center; justify-items: center;">O'quv reja bo'yicha ma'lumotlar yo'q.</h2>
            {% endfor %}

            <!-- O'quv raja tugadi -->
        </div>
    </div>
{% endblock %}

templates/main/talablar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="malaka">
        <div class="top-content">
            <div class="content">
                <nav class="top-bar">
                    <h3>
                        <i class="fa fa-users"></i>
                        Malaka talablari
                    </h3>
                    <nav>
                        <a href="{% url 'main:welcome' %}">
                            <i class="fa fa-home clfacebook"></i>
                        </a>
                        /
                        <i>
                            <a class="clfacebook" href="{% url 'main:welcome' %}">
                                malaka talablari
                            </a>
                        </i>
                    </nav>
                </nav>
            </div>
        </div>
        <div class="content">
            {% for requirement in requirements %}
                <a href="{{ requirement.file.url }}">
                    <nav>
                        <img src="{% static 'image/book.png' %}" alt="file.png">
                        <p>
                            {{ requirement.faculty.name_uz }} malaka talablari
                        </p>
                    </nav>
                </a>
                {% empty %}
                    <h2>Malaka talablari bo'yicha ma'lumotlar yo'q.</h2>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/main/tavsifnoma.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="malaka">
        <div class="top-content">
            <div class="content">
                <nav class="top-bar">
                    <h3>
                        <i class="fa fa-users"></i>
                        Malaka tavsifnomasi
                    </h3>
                    <nav>
                        <a href="{% url 'main:welcome' %}">
                            <i class="fa fa-home clfacebook"></i>
                        </a>/
                        <i>
                            <a class="clfacebook" href="{% url 'main:welcome' %}">
                                malaka tavsifnomasi
                            </a>
                        </i>
                    </nav>
                </nav>
            </div>
        </div>
        <!-- Malaka tavsifnoma -->
        <div class="content">
            <!-- Malaka tavsifnoma boshlandi -->
            {% for description in descriptions %}
                <a href="{{ description.file.url }}">
                    <nav>
                        <img src="{% static 'image/book.png' %}" alt="file.png">
                        <p>{{ description.faculty.name_uz }} malaka tavsifnomasi</p>
                    </nav>
                </a>
                {% empty %}
                <h2>Malaka tavsifnoma bo'yicha ma'lumotlar yo'q.</h2>
            {% endfor %}
        <! -- Malaka tavsifnoma tugadi -->
        </div>
    </div>
{% endblock %}

templates/main/welcome.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="home">
        <div class="sliders">
            <div class="slider">

            </div>
        </div>
        <div class="links">
            <div class="content">
                <nav class="link-box">
                    <a href="/https://hemis.tsdi.uz/" target="_blank">
                        <nav class="link">
                            <nav class="link-img"><img src="{% static 'image/teacher.png' %}" alt="">
                            </nav>
                            <h3>HEMIS-Teacher</h3>
                            <p>Toshkent davlat stomatologiya instituti Hemis tizimga O'qituvchilar kirish!</p>
                        </nav>
                    </a><a href="/https://student.tsdi.uz/" target="_blank">
                    <nav class="link">
                        <nav class="link-img"><img src="{% static 'image/student.png' %}" alt="">
                        </nav>
                        <h3>HEMIS-Student</h3>
                        <p>Toshkent davlat stomatologiya instituti Hemis tizimga Studentlar kirish!</p>
                    </nav>
                </a><a href="/https://moodle.tsdi.uz/" target="_blank">
                    <nav class="link">
                        <nav class="link-img"><img src="{% static 'image/moodle.png' %}" alt=""></nav>
                        <h3>Moodle tizimi</h3>
                        <p>Toshkent davlat stomatologiya instituti Moodle tizimiga kirish!</p>
                    </nav>
                </a><a href="https://library.tsdi.uz/" target="_blank">
                    <nav class="link">
                        <nav class="link-img"><img src="{% static 'image/xat.webp' %}" alt=""></nav>
                        <h3>Elektron kutubxona</h3>
                        <p>Toshkent Davlat Stomatologiya Instituti Elektron kutubxona tizimiga kirish!</p>
                    </nav>
                </a></nav>
            </div>
        </div>
        <div class="statistika">
            <div class="content">
                <div class="stat-circle">
                    <nav><h3><i class="fa fa-map"></i></h3><br>
                        <p style="text-align: center;">2578 ta <br>Talaba</p></nav>
                    <nav><h3><i class="fa fa-map"></i></h3><br>
                        <p style="text-align: center;">124 ta <br>Ustozlar</p></nav>
                    <nav><h3><i class="fa fa-map"></i></h3><br>
                        <p style="text-align: center;">1059 ta <br>1-Kurslar</p></nav>
                    <nav><h3><i class="fa fa-map"></i></h3><br>
                        <p style="text-align: center;">6 ta <br>O'quv bino</p>
                    </nav>
                </div>
            </div>
        </div>
        <div class="divider">
            <div class="content">
                <nav><h4><i class="fa fa-graduation-cap"></i> O`quv-uslubiy bo`lim</h4><br>
                    <p>Toshkent davlat Stamotologiya Instituti</p></nav>
                <ul class="divider-list">
                    <li><a href="/https://t.me/Developer1524"><i class="fa fa-paper-plane cltg"></i></a></li>
                    <li><a href="/"><i class="fa fa-twitter cltwitter"></i></a></li>
                    <li><a href="/"><i class="fa fa-facebook clfacebook"></i></a></li>
                    <li><a href="/"><i class="fa fa-youtube clyoutube"></i></a></li>
                    <li><a href="/"><i class="fa fa-instagram clinsta"></i></a></li>
                </ul>
            </div>
        </div>
        <div class="news">
            <div class="content">
                <nav class="news-title">
                    <hr>
                    <p>Bo`lim yangiliklari</p>
                    <hr>
                </nav>
                <div class="new-box">
                    {% for new in news %}
                        <nav class="new-body">
                            <nav class="new-time"><em>Yangilik |</em> {{ new.create_at | date:"d:m:Y" }} <i
                                    class="fa fa-eye">
                                {{ new.sees }}</i>
                            </nav>
                            <nav class="news-img"><img src="{{ new.image.url }}" alt="rasm">
                            </nav>
                            <p class="new-text">
                                <a href="{% url 'main:new' new.id %}">
                                    {{ new.title|slice:160 }}
                                </a>
                            </p>
                        </nav>
                    {% endfor %}

                </div>
            </div>
        </div>
        <div class="services" style="padding-bottom: 30px;">
            <div class="content">
                <nav class="serv"><a href="https://library.tsdi.uz/"><p>Elektron kutubxona</p></a></nav>
                <nav class="serv"><a href="https://yotoqxona.tsdi.uz/"><p>Yoqotxona qabul</p></a></nav>
                <nav class="serv"><a href="https://qabul.tsdi.uz/"><p>PIMU qabul</p></a></nav>
                <nav class="serv"><a href="https://student.tsdi.uz/dashboard/login"><p>Hemis Student</p></a></nav>
                <nav class="serv"><a href="https://moodle.tsdi.uz/login/index.php"><p>Moodle Student</p></a></nav>
                <nav class="serv"><a href="https://infox.edu.uz/site/login"><p>Info Edu</p></a></nav>
                <nav class="serv"><a href="https://phd.mininnovation.uz/"><p>Phd va Dcs</p></a></nav>
                <nav class="serv"><a href="https://app.ijro.uz/auth"><p>Idoralararo elektron tizim</p></a></nav>
                <nav class="serv"><a href="https://student.tsdi.uz/dashboard/diploma"><p>Diplomni tasdiqlash</p></a>
                </nav>
                <nav class="serv"><a href="https://edo.ijro.uz/welcome"><p>IJRO.GOV.UZ</p></a></nav>
            </div>
        </div>
    </div>

{% endblock %}